version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: babel-plugin-htmlbars-inline-precompile
    versions:
    - 4.2.1
    - 4.4.4
    - 4.4.5
    - 5.0.0
    - 5.2.1
    - 5.2.2
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: codemod-cli
    versions:
    - 3.1.1
  - dependency-name: chalk
    versions:
    - 4.1.0
  commit-message:
    prefix: ""
